# Sets up postgres container,
# may add persistent volumes if needed
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: devnet